server:
  port: 8080
  session:
    timeout: 43200
  tomcat:
    basedir: /home/ubuntu/tomcat_tmp

spring:
    session:
    datasource:
      name: test
      url: jdbc:mysql://localhost:3306/cms4j?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 'Mb123456'

wechat:
  applet:
    appId: wx1b06cc20dbfe8314
    secret: e574eaddbafe863e6b6325aa25a49042